// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/fcorrionero/go-restaurant/domain (interfaces: IngredientsRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	domain "github.com/fcorrionero/go-restaurant/domain"
	gomock "github.com/golang/mock/gomock"
)

// MockIngredientsRepository is a mock of IngredientsRepository interface.
type MockIngredientsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIngredientsRepositoryMockRecorder
}

// MockIngredientsRepositoryMockRecorder is the mock recorder for MockIngredientsRepository.
type MockIngredientsRepositoryMockRecorder struct {
	mock *MockIngredientsRepository
}

// NewMockIngredientsRepository creates a new mock instance.
func NewMockIngredientsRepository(ctrl *gomock.Controller) *MockIngredientsRepository {
	mock := &MockIngredientsRepository{ctrl: ctrl}
	mock.recorder = &MockIngredientsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIngredientsRepository) EXPECT() *MockIngredientsRepositoryMockRecorder {
	return m.recorder
}

// FindAllByIds mocks base method.
func (m *MockIngredientsRepository) FindAllByIds(arg0 []int) []*domain.Ingredient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByIds", arg0)
	ret0, _ := ret[0].([]*domain.Ingredient)
	return ret0
}

// FindAllByIds indicates an expected call of FindAllByIds.
func (mr *MockIngredientsRepositoryMockRecorder) FindAllByIds(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByIds", reflect.TypeOf((*MockIngredientsRepository)(nil).FindAllByIds), arg0)
}

// FindByName mocks base method.
func (m *MockIngredientsRepository) FindByName(arg0 string) *domain.Ingredient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", arg0)
	ret0, _ := ret[0].(*domain.Ingredient)
	return ret0
}

// FindByName indicates an expected call of FindByName.
func (mr *MockIngredientsRepositoryMockRecorder) FindByName(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockIngredientsRepository)(nil).FindByName), arg0)
}

// Save mocks base method.
func (m *MockIngredientsRepository) Save(arg0 domain.Ingredient) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Save", arg0)
}

// Save indicates an expected call of Save.
func (mr *MockIngredientsRepositoryMockRecorder) Save(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockIngredientsRepository)(nil).Save), arg0)
}
