// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/fcorrionero/go-restaurant/domain"
	"github.com/fcorrionero/go-restaurant/infrastructure/persistence/mongo"
)

// Injectors from wire.go:

func InitializeDishesRepository() domain.DishesRepository {
	dishesRepository := NewDishesRepository()
	return dishesRepository
}

// wire.go:

func NewDishesRepository() domain.DishesRepository {
	return mongo.New("root", "example", "0.0.0.0", "27017", "go-restaurant")
}
