version: '3.7'

services:
  mongo:
    image: mongo
    container_name: go_restaurant_mongo
    restart: always
    volumes:
      - go_restaurant_core_mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: go_restaurant_mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: go_restaurant_mysql
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: example
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - go_restaurant_core_mysql:/var/lib/mysql
    #  - ./mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  go_restaurant_core_mongo:
  go_restaurant_core_mysql: